#!/usr/bin/python
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89 ...
#
#Find the sum of all the even-valued terms in the sequence which do not exceed four million.

def fib_seq(MAX):
    n1 = 1
    n2 = 1
    summ = 0
    res = 0
    fib_arr = []

    while res < MAX:
        if not res % 2:
            summ += res

        res = n1 + n2
        fib_arr.append(res)
        n1 = n2
        n2 = res

    print(fib_arr)
    return summ


print("Sum %d" % fib_seq(4000000))
