/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, …

Find the sum of all the even-valued terms in the sequence which do not exceed four million.
*/

var MAX = 4000000;
var f1 = 1, f2 = 1, sum = 0, res = 0, fib_arr = [f1, f2];

while (res < MAX) {
  if (res % 2 === 0) {
    sum += res;
  }

  res = f1 + f2;
  fib_arr.push(res);
  f1 = f2;
  f2 = res;
}

console.log(fib_arr);
console.log(sum);
